-- calender_dim-- MySQL Script generated by MySQL Workbench
-- Mon Sep 13 00:38:14 2021
-- Model: New Model    Version: 1.0table_research_fact
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_warehouse` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `database_warehouse` ;

-- -----------------------------------------------------
-- Table `database_warehouse`.`calender_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`calender_dim` (
  `item_id` INT NOT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `week_day` VARCHAR(45) NULL DEFAULT NULL,
  `time_from` TIME NULL DEFAULT NULL,
  `time_to` TIME NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `flag` INT NULL DEFAULT NULL,
  `flag_description` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`department_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`department_dim` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`professors_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`professors_dim` (
  `professor_id` INT NOT NULL,
  `job_title` VARCHAR(100) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(1) NULL DEFAULT NULL,
  `contact_email` VARCHAR(100) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(25) NULL DEFAULT NULL,
  `office_number` VARCHAR(45) NULL DEFAULT NULL,
  `webpage` VARCHAR(100) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`publications_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`publications_dim` (
  `publication_id` INT NOT NULL,
  `publication_title` VARCHAR(150) NULL DEFAULT NULL,
  `publication_abstract` VARCHAR(6000) NULL DEFAULT NULL,
  `journal_name` VARCHAR(150) NULL DEFAULT NULL,
  `conference_name` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`publication_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`research_interest_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`research_interest_dim` (
  `research_area_id` INT NOT NULL,
  `research_area_title` VARCHAR(250) NULL DEFAULT NULL,
  `research_area_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`research_area_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`research_projects_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`research_projects_dim` (
  `research_project_id` INT NOT NULL,
  `research_project_title` VARCHAR(250) NULL DEFAULT NULL,
  `research_project_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`research_project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`research_students_dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`research_students_dim` (
  `student_id` INT NOT NULL,
  `student_name` VARCHAR(45) NULL DEFAULT NULL,
  `student_email` VARCHAR(100) NULL DEFAULT NULL,
  `research_project_title` VARCHAR(150) NULL DEFAULT NULL,
  `research_project_description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_warehouse`.`table_research_fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_warehouse`.`table_research_fact` (
`id` int auto_increment not null primary key,
  `research_area_id` INT NULL DEFAULT NULL,
  `research_project_id` INT NULL DEFAULT NULL,
  `student_id` INT NULL DEFAULT NULL,
  `publication_id` INT NULL DEFAULT NULL,
  `professor_id` INT NULL DEFAULT NULL,
  `department_id` INT NULL DEFAULT NULL,
  `item_id` INT NULL DEFAULT NULL,
  INDEX `fk_fact_academic_table_dim_research_interest_idx` (`research_area_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_research_project1_idx` (`research_project_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_research_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_publication1_idx` (`publication_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_professor1_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_fact_academic_table_dim_calender1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_fact_academic_table_dim_calender1`
    FOREIGN KEY (`item_id`)
    REFERENCES `database_warehouse`.`calender_dim` (`item_id`),
  CONSTRAINT `fk_fact_academic_table_dim_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `database_warehouse`.`department_dim` (`department_id`),
  CONSTRAINT `fk_fact_academic_table_dim_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `database_warehouse`.`professors_dim` (`professor_id`),
  CONSTRAINT `fk_fact_academic_table_dim_publication1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `database_warehouse`.`publications_dim` (`publication_id`),
  CONSTRAINT `fk_fact_academic_table_dim_research_interest`
    FOREIGN KEY (`research_area_id`)
    REFERENCES `database_warehouse`.`research_interest_dim` (`research_area_id`),
  CONSTRAINT `fk_fact_academic_table_dim_research_project1`
    FOREIGN KEY (`research_project_id`)
    REFERENCES `database_warehouse`.`research_projects_dim` (`research_project_id`),
  CONSTRAINT `fk_fact_academic_table_dim_research_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `database_warehouse`.`research_students_dim` (`student_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
